### ISSUE TITLE
`sweep-over-single-component-and-credit-supply` controllable scenario

### ISSUE THREAD

**Issue by danlessa** [BlockScience/subspace#26]
Parameters to be swept:

1. `default` issuance function, with `c` varying between 0.1 and 10
2. `credit_supply_definition`, by using both the `issued_supply` and the `total_supply` metrics
3. `reference_subsidy_components`, by using a single component consists of `[0, X_1, X_2, X_3]` where: `X_1` is between `1mo` and `12mo`, `X_2` is between 10% and 20% of `max_credit_supply` and `X_3` is between 0 and `X_2/X_1`. One departure point is to sample 3 points for each range and do a cartesian product. [`cadCAD_tools.preparation.sweep_cartesian_product`](https://github.com/cadCAD-org/cadCAD-tools/blob/main/cadCAD_tools/preparation.py) may give a quick starter here.

**Comment by LinuxIsCool** [comment]
I'll start by sampling 3 points, uniformly spaced for each interval. ie. a, (a+b)/2, b for [a,b].

**Comment by LinuxIsCool** [comment]
Note, the Test Plan originally said [10%, 80%] for `max_credit_supply`. I'm guessing that [10%,20%] is the correct range and I updated the Test Plan accordingly.

**Comment by LinuxIsCool** [comment]
@danlessa I'm concerned about performance. We have 3*2*3*3*3 = 162 controllable parameter sets. And we have 4 environmental parameter sets. 

Thus we have a total of 648 parameter sets. I'm finding that to just run a simulation of 1 day with 1 sample is taking about 15 minutes on my desktop PC. 

To run 1095 days with 30 samples will then take 312.5 days to run.

**Comment by LinuxIsCool** [comment]
Draft implementation here: https://github.com/BlockScience/subspace/blob/4e1e79d8f9b8d3b8b2617c05c3392498d249ef1c/subspace_model/experiments/experiment.py#L319

**Comment by LinuxIsCool** [comment]
Unfortunately the experiments are failing to complete. 

```
(🐍-subspace) ygg@pop-os ~/Workspace/BlockScience/subspace [main] 🪷 python -m subspace_model -e sweep_over_single_component_and_credit_supply -d 1095 -s 2 -p

2024-01-02 17:15:32 - subspace-digital-twin - INFO
------------subspace-digital-twin------------

2024-01-02 17:15:33 - subspace-digital-twin - INFO
Initializing main...

2024-01-02 17:15:33 - subspace-digital-twin - INFO
Setting log level to info...

2024-01-02 17:15:33 - subspace-digital-twin - INFO
Executing experiment: sweep_over_single_component_and_credit_supply...

                  ___________    ____
  ________ __ ___/ / ____/   |  / __ \
 / ___/ __` / __  / /   / /| | / / / /
/ /__/ /_/ / /_/ / /___/ ___ |/ /_/ /
\___/\__,_/\__,_/\____/_/  |_/_____/
by cadCAD

cadCAD Version: 0.5.1
Execution Mode: single_proc
Simulation Dimensions:
Entire Simulation: (Models, Unique Timesteps, Params, Total Runs, Sub-States) = (1, 1096, 43, 1296, 37)
     Simulation 0: (Timesteps, Params, Runs, Sub-States) = (1096, 43, 1296, 37)
Initializing configurations: 100%|██████████████████████████████████████████████████| 1296/1296 [00:06<00:00, 197.85it/s]
Execution Method: single_proc_exec
Execution Mode: single_threaded
fish: Job 1, 'python -m subspace_model -e swe…' terminated by signal SIGKILL (Forced quit)
                                                                                                      [ 16h 20m 22s864 ]
(🐍-subspace) ygg@pop-os ~/Workspace/BlockScience/subspace [main] 🪷      
```

Trying on another PC now.

**Comment by danlessa** [comment]
Hey @LinuxIsCool, try to use the `deepcopy_off` flag that was implemented in cadCAD 0.5.0 and lmk the results. If performance is still unacceptable, let's create another issue and continue it there

**Comment by LinuxIsCool** [comment]
Thanks @danlessa 

I'm now trying `deepcopy_off=True` as referenced here: https://github.com/cadCAD-org/cadCAD/blob/master/CHANGELOG.md#050---december-20-2023

Timings:
```
python -m subspace_model -e sweep_over_single_component_and_credit_supply -d 1 -s 1 -p
>>> 14.56s

python -m subspace_model -e sweep_over_single_component_and_credit_supply -d 2 -s 2 -p
>>> 36.77s
```

I'll now try a single run with 1095 days using `deepcopy_off=True`. 

```
python -m subspace_model -e sweep_over_single_component_and_credit_supply -d 1095 -s 1 -p
```
Will post results when they come in.

**Comment by LinuxIsCool** [comment]
Completed.
