### ISSUE TITLE
Update Model Implementation to Reflect Fees Rewards Specification 

### ISSUE THREAD

**Issue by LinuxIsCool** [BlockScience/subspace#35]
Our model implementation can be improved to meet this specification: 

https://subspacelabs.notion.site/Fees-Rewards-Specification-WIP-1b835c7684a940f188920802ca6791f2#4d2c4f4b69a94fcca49a7fcaca7563cc

This task can be broken down into: 

- [x] Add Consensus Extrinsic Fee state variable (CEF = StorageFees + ComputeFees + PriorityFees)
- [x] Change Storage Fee terminology (eg. Storage Fee = StorageFeePerByte * ExtrinsicLengthInBytes)
- [x] Refactor Storage Fee logic
- [x] Implement Compute Fee Multiplier Logic & State Variable
- [x] Re-Implement Compute Fee Logic (Slow Adjusting Fee mechanism)
- [x] Refactor Compute Fee so that the Bundle-relevant fees goes to Operators rather than Proposing Farmers
- [x] (any others)

**Comment by LinuxIsCool** [comment]
Partial progress posted here: https://github.com/blockscience/subspace/tree/fee_rewards_specification

Working on the compute fee now.

**Comment by danlessa** [comment]
13 Feb: it's very close to being done

**Comment by LinuxIsCool** [comment]
Update from Dariia

- [ ] Ensure that minimum compute fee is 1 Shannon instead of 1 SSC
