### ISSUE TITLE
Determine System Response to History Size being larger than Space Pledged

### ISSUE THREAD

**Issue by danlessa** [BlockScience/subspace#43]
A/C: 
- [x] we have a answer to "`total_space_pledge > history_size * min_replication_factor` by definition.  What happens if this occurs is a good question to ask btw"
- [ ] Make sure that the model implements the correct response

**Comment by danlessa** [comment]
Answer: unexpected. Therefore, the System Response is to be modeled by raising a ValueError Exception.

**Comment by LinuxIsCool** [comment]
@danlessa to confirm,  the exception should be raised when `total_space_pledge <= history_size * min_replication_factor`

**Comment by LinuxIsCool** [comment]
In this case, it looks like the exception is being raised in the first iteration of standard_stochastic_run. 

```
total_space_pledged=1.57e+12
blockchain_history_size=2.04e+12
min_replication_factor=5.00e+01
```

I'll continue to investigate.

**Comment by LinuxIsCool** [comment]
Closing and moving on to pledging space behavioral model.
