### ISSUE TITLE
Distill main points from “Tokenomics Decision Making Forum” discussion

### ISSUE THREAD

**Issue by danlessa** [BlockScience/subspace#47]
https://www.notion.so/Tokenomics-Decision-Making-Forum-441f1a95016d4fe28ac22abcc1367253#f1985e21cb10450baafddc2b64764e96

Distill main points from “Tokenomics Decision Making Forum” discussion into:
- Parameters that need to be decided (called “governance surface” - For each question, what is the relevant governance surface)
- Relevant goals & constraints
- KPIs that reflect a system goal or desirable mentioned
- Environmental scenario that reflects behavior mentioned
- New experiments (combining scenarios and parameters)

a/c: ?

**Comment by phacker3** [comment]
a/c: document on HackMD outline our strategy for reaching decisions on the tokenomics decision making forum. (description on how we get to decisions)

**Comment by phacker3** [comment]
move to done, opening a new story for 1st a/c
