### ISSUE TITLE
update issuance function default hyperbolic parameters to dariia's proposal

### ISSUE THREAD

**Issue by LinuxIsCool** [BlockScience/subspace#50]
A/C:
- update experiment list to reflect this
- update experiment code to reflect this
- update default parameterization (params.py) to reflect this

**Comment by LinuxIsCool** [comment]
So far, i've spent 2 hours familiarizing myself with this documentation: https://subspacelabs.notion.site/Dynamic-Issuance-Specification-3bdf63955cb943489347889775d71c24

I'm temporarily blocked, attending to #33

**Comment by LinuxIsCool** [comment]
Completed #33 and had a really good connection call with Dariia.

- [ ] @danlessa @phacker3 you can watch the recorded discussion regarding this document: https://subspacelabs.notion.site/Dynamic-Issuance-Specification-3bdf63955cb943489347889775d71c24


Expanded the story points on this issue to 21. Consider the following subtasks:
- [ ] Review https://subspacelabs.notion.site/Dynamic-Issuance-Specification-3bdf63955cb943489347889775d71c24 with Dariia
- [ ] Digest the above document
- [ ] Introduce Spline Vs Functional Issuance Components
- [ ] A/B test Spline vs. Functional Issuance with default parameters
- [ ] Receive Update Mainnet parameters from @dariolina 
- [ ] Introduce Updated parameters into issuance A/B test
- [ ] Introduce updated parameters into standard battery

**Comment by phacker3** [comment]
proposing some changes to hopefully help clarify this task!

- Update title to: Update issuance function to reflect dariia's spec
- Update remaining subtasks to:
	- [ ] implement simplified issuance function described in Dariia's spec
	- [ ] Update Reference Subsidy components in cadCAD model with the parameters described in Dariia's spec in the section "Off-chain Issuance curve parameters setting" (note: we are NOT implementing the manual breakpoints for reference subsidy)
	- [ ] Implement logic for Voter Rewards
	- [ ] + add additional subtasks after completing the task [Scope out tasks to implement any remaining divergences that will be required for PSuU](https://github.com/orgs/BlockScience/projects/20/views/2?filterQuery=-status%3ADone%2C%22Won%27t+do+%2F+Invalid%22%2C%22Work+stream+-+Closed%22&pane=issue&itemId=56990707")

**Comment by LinuxIsCool** [comment]
This issue is superseded by #50
