### ISSUE TITLE
Implement PSuU for Subspace Model

### ISSUE THREAD

**Issue by LinuxIsCool** [BlockScience/subspace#56]
as per https://hackmd.io/iFeP7NemRH--KtWbPP_W0w

**Comment by LinuxIsCool** [comment]
I've made this my top priority as it will be the framework used to address all of the other issues. A lot of other issues will be resolved by achieving this. The PSuU document is the clearest definition of production model delivery that we have. The clarity makes it easier to achieve. Thus working on this as single priority makes sense to me.

**Comment by phacker3** [comment]
Subtasks discussed:
- [ ] implement new governance surface parameters (update mechanisms where required)
- [ ] implement Environmental Scenarios (all environmental variables exist, covariance/shock features for behaviors, build Scenario groups as specified)
- [ ] implement Metrics as specified
- [ ] implement KPIs & Thresholds as specified
- [ ] refactor things to feed [cadCAD machine search](https://github.com/cadCAD-org/cadCAD_machine_search) tooling which will enable the final PSuU analysis
